마커들의 중심으로 클러스터링 하는 옵션 추가
navermaps/marker-tools.js pull request #2
Opened 2017-04-14 08:45 UTC by cs09g

안녕하세요,

마커 클러스터링 옵션 중 위치에 관한 기능입니다.
기존에는 존재하는 마커의 위치 중 하나로 클러스터링이 되고 있는데요, averageCenter: true 옵션 설정 시, 마커들의 중심으로 클러스터링 되도록 하였습니다.

2017-04-15 01:56 UTC, thetaiz commented
@cs09g 님, 감사합니다. ^^ 차주에 확인하겠습니다.

2017-04-20 01:37 UTC, thetaiz requested changes
몇 가지 수정 요청을 드립니다. 감사합니다.

2017-04-20 01:37 UTC, thetaiz commented on marker-clustering/src/MarkerClustering.js
> +	 * @param {Array <naver.maps.Marker>} markers 마커 배열
Array.<naver.maps.Marker> 로 작성해 주세요.

2017-04-20 01:37 UTC, thetaiz commented on marker-clustering/src/MarkerClustering.js
> +			if (this._markerClusterer.getOptions().averageCenter) {
`getOptions` 메서드를 이용해 접근하는 것 보다는 `averageCenter` 옵션은 `getter/setter` 메서드를 만들고, 해당 메서드를 이용해 접근하는게 좋겠습니다. 더불어 `averageCenter` 옵션을 변경했을 때 처리(`changed` 참조)도 필요해 보입니다.

2017-04-20 01:58 UTC, cs09g commented on marker-clustering/src/MarkerClustering.js
> +			if (this._markerClusterer.getOptions().averageCenter) {
1. getter/setter 생성 시, _getAverageCenter 메소드와 이름이 겹쳐서 기존의 _getAverageCenter는 _calcAverageCenter 로 변경해도 괜찮을까요?

2. 옵션 변경 후, _redraw() 호출하니 위치 업데이트가 잘 되는 것 같습니다.
case 'gridSize': 아래 case 'averageCenter': 추가하도록 하겠습니다.

2017-04-20 02:10 UTC, thetaiz commented on marker-clustering/src/MarkerClustering.js
> +			if (this._markerClusterer.getOptions().averageCenter) {
@cs09g 넵 ^^ 괜찮습니다.

2017-04-26 07:51 UTC, boxersb commented on marker-clustering/src/MarkerClustering.js
> +	_calcAverageCenter: function(markers) {
좌표를 모두 더한다음, 마커의 개수로 나누는것 보다는..
각 마커를 돌면서 최대/최소 좌표를 구하여, bounds 객체 (naver.maps.PointBounds) 를 만든 다음, getCenter() 메서드로 중심점을 알아내는것이 보다 정확도가 높아질것 같습니다.

2017-04-26 08:30 UTC, junthus commented on marker-clustering/src/MarkerClustering.js
> +	_calcAverageCenter: function(markers) {
음... 마커 갯수에 대한 가중치가 있는편이 좋지 않을까요 ?.?

2017-04-26 08:35 UTC, cs09g commented on marker-clustering/src/MarkerClustering.js
> +	_calcAverageCenter: function(markers) {
모든 마커의 합을 나누는 것이, 마커가 많이 몰린 곳으로 중심점이 이동하기 때문에 더 좋을 것 같습니다.

2017-04-26 22:18 UTC, junthus commented on marker-clustering/src/MarkerClustering.js
>  };
![image](https://cloud.githubusercontent.com/assets/5088669/25427080/5a1d4c40-2aac-11e7-97fe-443fa8ee1898.png)

나쁜 케이스로 위치가 집약된 데이터의 경우 클러스터링 마커간의 거리가 매우 가까워 져서 클러스터링 마커끼리 겹쳐 보이는 현상이 생길 수 있을 듯 한데요.

물론 `averageCenter` 옵션으로 어느정도 중심점에 대한 정보는 추가할 수 있어 의미는 있지만
클러스터링이 제대로 안 된 것 같은 화면이 노출될 수 있다는 점에서 고민이 됩니다 ㅎㅎ

저의 개인적인 바람으로는 이미 만들어진 클러스터의 센터값 업데이트가 아닌... 
균일한 클러스터의 생성에 대한 재능기부를....

ㅎㅎㅎ 의견들 주세요.

2017-04-27 01:56 UTC, cs09g commented on marker-clustering/src/MarkerClustering.js
>  };
클러스터링 마커끼리 겹치는 것은 기준 거리가 짧고, 클러스터링 마커가 아주 큰 경우가 아니라면 발생할 경우가 적을 것 같습니다. 클러스터링 마커는 주변에 하위 마커가 많음을 나타내기 위함인데, 평균 값을 사용하지 않으면 [클러스터데모](https://navermaps.github.io/marker-tools.js/marker-clustering/marker-clustering.html) 의 0레벨에서 울릉도의 사망사고가 급격히 늘어나는것 같은 결과를 가져올수도 있습니다.

2017-04-27 05:29 UTC, junthus commented on marker-clustering/src/MarkerClustering.js
>  };
@cs09g 아 저 예제는 좋은 증거네요 b(ㅠ.ㅠ)b `averageCenter` 를 사용할 때의 워스트케이스보다 현재 구현의 워스트케이스가 더 문제가 된다는 점에서 저도 approve 입니다.

2017-04-27 05:30 UTC, junthus commented
@thetaiz @boxersb 머지해도 될까유 ?.? 더 이견들 없으시죠 ?

2017-04-27 05:36 UTC, thetaiz approved these changes

2017-04-27 05:36 UTC, thetaiz commented
@boxersb @junthus 넵, 이견 없습니다.

2017-04-27 05:37 UTC, junthus approved these changes

2017-04-27 06:02 UTC, boxersb commented on marker-clustering/src/MarkerClustering.js
> +		return new naver.maps.LatLng(averageCenter[1], averageCenter[0]);
네.. 이해가 되었습니다만.. 리턴 값은 LatLng 가 아니라 Point 객체로 해주시는게 어떨지 의견 드립니다.

LatLng 좌표를 쓰는 지도유형만을 쓸것 같지는 않아서요 ^^

2017-04-27 06:21 UTC, cs09g commented on marker-clustering/src/MarkerClustering.js
> +		return new naver.maps.LatLng(averageCenter[1], averageCenter[0]);
Point 로 모두 커버가 가능한가요? Marker 의 Position 타입에 따라 Point / LatLng 를 나누어 주어야 할 것 같은 느낌이 듭니다...

2017-11-28 08:48 UTC, cs09g commented on marker-clustering/src/MarkerClustering.js
> +		return new naver.maps.LatLng(averageCenter[1], averageCenter[0]);
@boxersb 오래 지나버렸지만... 의견 부탁드립니다 :)

2017-11-28 08:49 UTC, boxersb commented on marker-clustering/src/MarkerClustering.js
> +		return new naver.maps.LatLng(averageCenter[1], averageCenter[0]);
@cs09g 네.. Point의 x, y로 모두 커버 됩니다. LatLng 는 위/경도를 다루는데 편의를 주기 위해, lat = y, lat = x 에 바인딩 되어 있습니다.

2017-11-28 09:24 UTC, boxersb commented
@cs09g 님.. 이 오픈소스 프로젝트에 대한 담당자가 변경되었습니다. 앞으로는, @ahnbj2000 님께 문의 부탁드립니다.
@ahnbj2000 님.. 이 PR 검토 후 머지 여부 결정해주시면 좋겠습니다.

2017-11-28 09:26 UTC, cs09g commented
@boxersb 네, 알겠습니다!
@ahnbj2000 의견 모두 반영했습니다. 확인부탁드립니다.

2017-12-01 06:20 UTC, merged